# Generated by Django 4.1.2 on 2022-10-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('format', models.CharField(max_length=15)),
                ('email_to', models.CharField(blank=True, max_length=100, null=True)),
                ('export_type', models.CharField(blank=True, max_length=25, null=True)),
                ('export_time', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
